// %BANNER_BEGIN%
// ---------------------------------------------------------------------
// %COPYRIGHT_BEGIN%
// Copyright (c) (2018-2022) Magic Leap, Inc. All Rights Reserved.
// Use of this file is governed by the Software License Agreement, located here: https://www.magicleap.com/software-license-agreement-ml2
// Terms and conditions applicable to third-party materials accompanying this distribution may also be found in the top-level NOTICE file appearing herein.
// %COPYRIGHT_END%
// ---------------------------------------------------------------------
// %BANNER_END%

using System;
using System.Runtime.InteropServices;
using UnityEngine.XR.MagicLeap.Native;

namespace UnityEngine.XR.MagicLeap
{
    /// <summary>
    /// API for converting between system and runtime clock timestamps.
    /// </summary>
    public partial class MLTime
    {
        /// <summary>
        /// Mirrors time.h's timespec struct, which is generated by clock_gettime()
        /// </summary>
        [StructLayout(LayoutKind.Sequential)]
        internal struct TimeSpec
        {
            public long Seconds;

            public long Nanoseconds;
        }
        
        /// <summary>
        /// See ml_time.h for additional comments.
        /// </summary>
        internal class NativeBindings : MagicLeapNativeBindings
        {
            [DllImport(MLPerceptionClientDll, CallingConvention = CallingConvention.Cdecl)]
            public static extern MLResult.Code MLTimeConvertSystemTimeToMLTime(IntPtr timeSpec, out long mlTime);

            [DllImport(MLPerceptionClientDll, CallingConvention = CallingConvention.Cdecl)]
            public static extern MLResult.Code MLTimeConvertMLTimeToSystemTime(long mlTime, IntPtr timeSpec);
        }
    }
}
